# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/logicarchive_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Tejas@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
file.upload.code-dir=uploads/code
file.upload.resource-dir=uploads/resource

# Logging
logging.level.com.logicarchive=DEBUG
logging.level.org.springframework.web=INFO
